---
name: GitHub Pages test deployment

on:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    name: GitHub Pages test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: Test build
        run: |
          yarn install --frozen-lockfile
          yarn build
