---
name: GitHub Pages test deployment

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-deploy:
    name: GitHub Pages test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Test build
        run: |
          npm ci
          npm run build
